#!/bin/sh
#***********************************************************************
#
#	$Id: geosteiner_config.in,v 1.4 2016/09/05 12:14:37 warme Exp $
#
#	File:	geosteiner_config.in
#	Rev:	e-2
#	Date:	09/05/2016
#
#	Copyright (c) 2003, 2016 by David M. Warme.  This work is
#	licensed under a Creative Commons Attribution 4.0 International
#	License.
#
#***********************************************************************
#
#	Script to configure client programs that use GeoSteiner.
#
#***********************************************************************
#
#	Modification Log:
#
#	a-1:	08/25/2003	warme
#		Created.
#	e-1:	04/14/2015	warme
#		: Changes for 5.0 release.
#	e-2:	09/05/2016	warme
#		: Change notices for 5.1 release.
#
#***********************************************************************

me="$0"

usage () {
	echo "Usage: $me [OPTIONS]"	2>&1
	echo "Options:"			2>&1
	echo "	[--version]"		2>&1
	echo "	[--libs]"		2>&1
	echo "	[--cflags]"		2>&1

	exit 1
}

case $# in
  0)	usage	;;
  *)	;;
esac

while [ "$#" -gt 0 ]
do
	case ".$1" in
	.--version)	echo "5.1.0"
			;;
	.--libs)	echo "-L/data/ssd/jwliu/rest/algorithms/geosteiner -lgeosteiner   -lm"
			;;
	.--cflags)	echo "-I/data/ssd/jwliu/rest/algorithms/geosteiner"
			;;
	*)		usage
			;;
	esac
	shift
done
