base:
  seed: 0
  # ckpt_path: checkpoint/
  ckpt_path: None
  ckpt_dir: checkpoint/
  log_dir: logs/
  result_dir: result/
  model_name: FMCG_VAE_REST_64
  batch_size: 64
  max_epochs: 200
  latent_size: 64

model:
  loss_ema: True
  lr: 0.0001
  lr_decay_steps: 10
  lr_decay_rate: 0.96
  num_sample: 10
  vae_config:
    target: models.vae.VAE
    params:
      in_channels: 2
      out_channels: 1
      c_in_channels: 1
      latent_size: 64
      ngf: 64
      n_downsampling: 2
      use_dropout: True
      n_blocks: 9
      padding_type: zero
      size: 64

data:
  num_workers: 16
  target: data.aligned.AlignedDataset
  params:
    data_folder: dataset/
    condition_folder: REST_input_64
    route_folder: REST_64
    max_dataset_size: 200000
    restrict_c_channels: 1