base:
  seed: 1
  # ckpt_path: checkpoint/
  ckpt_path: None
  ckpt_dir: checkpoint/
  log_dir: logs/
  result_dir: result/
  model_name: FMCG_GAN_REST_64
  batch_size: 64
  max_epochs: 200
  lambda_norm: 100
  lambda_focal: 100

model:
  loss_ema: True
  lr: 0.0001
  lr_decay_steps: 10
  lr_decay_rate: 0.96
  num_sample: 10
  generator_config:
    target: models.gan.ResnetGenerator
    params:
      input_nc: 1
      output_nc: 1
      ngf: 64
      n_downsampling: 2
      use_dropout: True
      n_blocks: 9
      padding_type: zero
  discriminator_config:
    target: models.gan.Discriminator
    params:
      input_nc: 2
      ndf: 64
      n_layers: 3 
      use_dropout: False

data:
  num_workers: 16
  target: data.aligned.AlignedDataset
  params:
    data_folder: dataset/
    condition_folder: REST_input_64
    route_folder: REST_64
    max_dataset_size: 200000
    restrict_c_channels: 1