data:
  num_workers: 16
  rsmt: REST
  target: data.aligned.AlignedDataset
  params:
    data_folder: dataset/
    condition_folder: REST_input_test_64
    route_folder: REST_test_64
    max_dataset_size: 200000
    restrict_c_channels: 1
    restrict_dir: degree_50


